### ISSUE TITLE
Regarding Python 3 Support

### ISSUE THREAD

**Issue by ZaidQureshi** [shapeblue/ipmisim#1]
Hi,

So I am tying to port your library to Python 3 (using 2to3 and some library changes like SocketServer to socketserver) but am coming across a weird problem.
When I run ipmisim.py with python2 everything runs fine. The server responds to commands from ipmitool.
With python3, the server initilizes and even establishes the session when a command from ipmitool is initiated, but ipmitool gets an error with trying to get Get Auth Capabilities, reporting:
"Get Auth Capabilities error.
Error issuing Get Channel Authentication Capabilities request
Error: Unable to establish IPMI v2 /RMCP+ session"
The server reports that a new IPMI session has been initialized for this client. So I am not sure where the problem is. 

**Update**
So there were some python 2 and python 3 conflicts having to do with bytes and strings. I believe I fixed them but now the ipmitool client isn't receiving the rakp2 payload from the IPMI server, the client tries to get this 4 times but never receives it. I am sure the server is receiving the appropriate rakp1 request and sends a packet of length 94 back each of the 4 times (checked via wireshark). I am not sure what is missing. I looked over the send_payload method in fakesession.py but there doesn't seem to any byte and strings conflicts.

**Comment by yadvr** [comment]
are you using admin:password as credentials? you can debug if udp payload is being sent/received by increasing verbosity on `ipmitool` -vvvv. 

The implementation was specific to Python 2.7, unfortunately I may not be able to invest time to port this on Python 3 myself much any contribution is welcome.

**Comment by ZaidQureshi** [comment]
So the problem was with the username strings. I was able to convert it completely to python 3.
