### ISSUE TITLE
ipmisim appears to *really* not like freeipmi

### ISSUE THREAD

**Issue by lf-** [shapeblue/ipmisim#3]
`ipmi-chassis -h 127.0.0.1:9001 -u user -p userpassword --chassis-control=POWER-UP`

Logs include repeated connections, but no actual activity. Eventually it gives up.

https://gist.github.com/7dd3e5e43d67b7c3d90c15cd8005a6c4 is a debug log.

**Comment by lf-** [comment]
Upon further inspection, it seems that ipmisim doesn't work *at all*. I tried the example in the readme and it fails to establish session even with ipmitool. Absolutely nothing in the logs for that one.

`ipmitool -I lanplus -H localhost -p 9000 -R1 -U admin -P password chassis power status`

**Comment by yadvr** [comment]
It's possible it does not work. This is for testing purposes only.

**Comment by yadvr** [comment]
It's only support for ipmitool.
