### ISSUE TITLE
Not reachable with ipmitool?

### ISSUE THREAD

**Issue by NotThatJonSmith** [shapeblue/ipmisim#4]
Maybe I'm just doing something wrong here, but I start the server:
$ ipmisim
2017-09-08 15:05:26,549 - ipmisim - INFO - IPMI BMC initialized.
2017-09-08 15:05:26,549 - ipmisim - INFO - CloudStack IPMI Sim BMC initialized
2017-09-08 15:05:26,549 - ipmisim - INFO - Started IPMI Server on 0.0.0.0:9001

and in another terminal:
$ ipmitool -I lanplus -H localhost -p 9001 -R1 -U admin -P password chassis power status
Error: Unable to establish IPMI v2 / RMCP+ session

Any ideas what's going on here?

**Comment by CJLove** [comment]
You can try ipmitool -v (or -vv or -vvv) to see more details.  The above command works for me, even with ipmitool 1.8.18 built from source.

We have application code sending the "get channel auth cap" command as an IPMIV2 message  and I found that the initiate_session() method doesn't handle it or respond correctly.  I've submitted a PR to fix this.

**Comment by yadvr** [comment]
@NotThatJonSmith likely the password is wrong. I'm unable to see such an error.
