### ISSUE TITLE
Ported to Python 3 Compatible

### ISSUE THREAD

**Issue by gzock** [shapeblue/ipmisim#7]
Thank you for the cool tool. I often use ipmisim. 
I have ported ipmisim to python3.
Can I fork this repositoriy and publish it as ipmisim3?
Or is a pull request better?

Zaid Qureshi, who previously develop it work on python3, seems not to publish it.

**Comment by yadvr** [comment]
Go ahead @gzock, I may add support for python3 but I don't have time. If you can make ipmisim work for both python2 and python3 - do send a PR!

**Comment by gzock** [comment]
@rhtyd Thank you for reply. I implemented ipmisim working for python2-3. I send PR.
